services:
    php:
        # Matches the composer.json floor (php >=8.4)
        image: php:8.4-cli
        working_dir: /app
        volumes:
            - type: bind
              source: ./
              target: /app
        command:
            -  tail
            - -f
            - /dev/null
